name = "DirWorkflow"
uuid = "af77908b-fbd1-5c81-abc0-13a9534196fe"
authors = ["singularitti <singularitti@outlook.com>"]
version = "0.1.0"

[workspace]
projects = ["test", "docs"]

[compat]
julia = "1.10"
