name = "DirWorkflow"
uuid = "af77908b-fbd1-5c81-abc0-13a9534196fe"
version = "0.1.0"
authors = ["singularitti <singularitti@outlook.com>"]

[workspace]
projects = ["test", "docs"]

[deps]
FileTrees = "72696420-646e-6120-6e77-6f6420746567"

[compat]
FileTrees = "0.3.10"
julia = "1.10"
