[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
DirWorkflow = "af77908b-fbd1-5c81-abc0-13a9534196fe"

[compat]
Documenter = "1"

[sources]
DirWorkflow = {path = ".."}
